# Generated by Django 4.2.11 on 2024-05-02 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
